// src/vue/sheets/header/partials/AbilityScore.vue
<template>
  <li
    class="
      u-align-center
      u-bg-gray
      u-flex
      u-flex-col
      u-font-serif
      u-py-xs
      u-rounded
      u-w-full
    "
  >
    <h4 class="u-text-lg">{{ ability.label }}</h4>

    <div v-if="sheetIsLocked" class="a5e-ability-score__value">
      {{ ability.value }}
    </div>

    <input
      v-else
      class="a5e-ability-score__value"
      :name="`data.abilities.${label}.value`"
      type="number"
      :value="ability.value"
      placeholder="10"
    />

    <div
      class="a5e-ability-score__buttons"
      :class="{ 'u-justify-center u-gap-lg': sheetIsLocked }"
    >
      <div
        class="a5e-ability-score__roll-button"
        :title="localize('A5E.RollAbilityCheck')"
        @click="onRollAbilityCheck(label)"
      >
        {{ ability.check.deterministicBonus }}

        <div class="a5e-tooltip a5e-tooltip--ability-score">
          {{ localize("A5E.RollAbilityCheck") }}
        </div>
      </div>

      <i
        v-if="!sheetIsLocked"
        class="a5e-config-button fas fa-cog"
        :title="localize('A5E.ConfigureBonuses')"
        @click="onClickConfigButton(label)"
      ></i>

      <div
        class="a5e-ability-score__roll-button a5e-js-roll-saving-throw"
        :title="localize('A5E.RollSavingThrow')"
        @click="onRollSavingThrow(label)"
      >
        {{ ability.save.deterministicBonus }}

        <div
          class="a5e-tooltip a5e-tooltip--ability-score"
          :class="{ 'a5e-tooltip--obstacle-right': label === 'cha' }"
        >
          {{ localize("A5E.RollSavingThrow") }}
        </div>
      </div>
    </div>
  </li>
</template>

<script>
import { inject } from "vue";

export default {
  props: { ability: Object, label: String, sheetIsLocked: Boolean },
  setup() {
    const actor = inject("actor");

    function onClickConfigButton(ability) {
      actor.configureAbilityScore(ability);
    }

    function onRollAbilityCheck(ability) {
      actor.rollAbilityCheck(ability);
    }

    function onRollSavingThrow(ability) {
      actor.rollSavingThrow(ability);
    }

    return {
      localize: (key) => game.i18n.localize(key),
      onClickConfigButton,
      onRollAbilityCheck,
      onRollSavingThrow,
    };
  },
};
</script>

// src/apps/components/AbilityScore.svelte
<script>
    import rollAbilityCheck from "../handlers/rollAbilityCheck";
    import rollSavingThrow from "../handlers/rollSavingThrow";

    import localize from "../utils/localize";
    import updateDocumentDataFromField from "../utils/updateDocumentDataFromField";

    export let ability;
    export let abilityLabel;
    export let actor;
</script>

<div>
    <li
        class="u-align-center u-bg-gray u-flex u-flex-col u-font-serif u-py-xs u-rounded u-w-full"
    >
        <input
            class="a5e-ability-score__value"
            name={`system.abilities.${abilityLabel}.value`}
            type="number"
            value={ability.value}
            on:change={({ target }) =>
                updateDocumentDataFromField($actor, target.name, target.value)}
            placeholder="10"
        />

        <div class="a5e-ability-score__buttons">
            <div
                class="a5e-ability-score__roll-button a5e-js-roll-saving-throw"
                title={localize("A5E.RollSavingThrow")}
                on:click={(event) =>
                    rollAbilityCheck($actor, abilityLabel, event)}
            >
                {ability.check.deterministicBonus}

                <div class="a5e-tooltip a5e-tooltip--ability-score">
                    {localize("A5E.RollSavingThrow")}
                </div>
            </div>

            <div
                class="a5e-ability-score__roll-button a5e-js-roll-saving-throw"
                title={localize("A5E.RollSavingThrow")}
                on:click={(event) =>
                    rollSavingThrow($actor, abilityLabel, event)}
            >
                {ability.save.deterministicBonus}

                <div class="a5e-tooltip a5e-tooltip--ability-score">
                    {localize("A5E.RollSavingThrow")}
                </div>
            </div>
        </div>
    </li>
</div>
