// src/vue/sheets/pages/partials/TabFooter.vue
<template>
  <footer
    class="
      u-bg-light
      u-border-t
      u-border-gray
      u-bottom-0
      u-flex
      u-font-serif
      u-justify-space-between
      u-left-0
      u-pos-absolute
      u-px-xxl
      u-py-md
      u-text-lg
      u-w-full
    "
  >
    <slot></slot>
  </footer>
</template>

// src/apps/components/TabFooter.svelte
<script>
</script>

<footer class="tab-footer">
    <slot />
</footer>

<style lang="scss">
    .tab-footer {
        display: flex;
        flex-wrap: wrap;
        gap: 0.25rem;
        align-items: center;
        justify-content: space-between;
        font-size: var(--a5e-text-size-sm);
        padding-right: var(--padding-right, 0);
    }
</style>
