// src/apps/components/itemPropertiesConfig/SpellConfiguration.svelte
<script>
    import { getContext } from "svelte";
    import { localize } from "#runtime/svelte/helper";

    import objectEntriesNumberKeyConverter from "../../../utils/objectEntriesNumberKeyConverter";
    import updateDocumentDataFromField from "../../../utils/updateDocumentDataFromField";

    import Checkbox from "../Checkbox.svelte";
    import CheckboxGroup from "../CheckboxGroup.svelte";
    import FormSection from "../FormSection.svelte";
    import RadioGroup from "../RadioGroup.svelte";
    import Tag from "../Tag.svelte";

    function prepareSpellComponents(item) {
        return Object.entries(item.system.components)
            .filter(([_, state]) => state)
            .map(
                ([component]) =>
                    spellComponentAbbreviations[component] ?? component
            )
            .join(", ");
    }

    function prepareSecondarySpellSchools(item) {
        const schools = item.system.schools.secondary.map(
            (school) => spellSchools.secondary[school] ?? school
        );

        schools.sort((a, b) => a.localeCompare(b));

        return schools.join(", ");
    }

    const item = getContext("item");

    const {
        spellComponents,
        spellComponentAbbreviations,
        spellLevels,
        spellSchools,
    } = CONFIG.A5E;

    let editMode = false;

    $: selectedSpellComponents = prepareSpellComponents($item);
    $: selectedSecondarySpellSchools = prepareSecondarySpellSchools($item);
</script>

<section>
    <!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
    <header
        class="
            u-align-center
            u-flex
            u-font-serif
            u-gap-md
            u-mb-lg
            u-ml-xs
            u-pointer
            u-text-lg
            u-w-fit
        "
        on:click={() => (editMode = !editMode)}
    >
        <h3>{localize("A5E.TabSpellConfiguration")}</h3>

        <i
            class="u-text-sm fas"
            class:fa-chevron-up={editMode}
            class:fa-edit={!editMode}
        />
    </header>

    {#if editMode}
        <div class="u-flex u-flex-col u-gap-md">
            <FormSection heading="A5E.SpellLevel">
                <RadioGroup
                    options={objectEntriesNumberKeyConverter(spellLevels)}
                    selected={$item.system.level}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.level",
                            event.detail
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.SpellSchoolPrimary">
                <RadioGroup
                    options={Object.entries(spellSchools.primary)}
                    selected={$item.system.schools.primary}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.schools.primary",
                            event.detail
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.SpellSchoolSecondaryPlural">
                <CheckboxGroup
                    options={Object.entries(spellSchools.secondary)}
                    selected={$item.system.schools.secondary}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.schools.secondary",
                            event.detail
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.SpellComponents">
                <ul
                    class="u-flex u-flex-wrap u-gap-sm u-list-style-none u-m-0 u-p-0 u-text-xs u-w-full"
                >
                    {#each Object.entries(spellComponents) as [value, label]}
                        <Tag
                            {label}
                            {value}
                            active={$item.system.components[value]}
                            on:tagToggle={() =>
                                updateDocumentDataFromField(
                                    $item,
                                    `system.components.${value}`,
                                    !$item.system.components[value]
                                )}
                        />
                    {/each}
                </ul>
            </FormSection>

            {#if $item.system.components.material}
                <FormSection heading="A5E.SpellMaterials">
                    <div class="u-w-full">
                        <input
                            class="a5e-input"
                            type="text"
                            name="system.materials"
                            value={$item.system.materials}
                            on:change={({ target }) =>
                                updateDocumentDataFromField(
                                    $item,
                                    target.name,
                                    target.value
                                )}
                        />
                    </div>
                </FormSection>
            {/if}

            <FormSection --gap="0.5rem 1.25rem">
                <Checkbox
                    label="A5E.SpellConcentration"
                    checked={$item.system.concentration}
                    on:updateSelection={({ detail }) => {
                        updateDocumentDataFromField(
                            $item,
                            "system.concentration",
                            detail
                        );
                    }}
                />

                <Checkbox
                    label="A5E.ItemPrepared"
                    checked={$item.system.prepared}
                    on:updateSelection={({ detail }) => {
                        updateDocumentDataFromField(
                            $item,
                            "system.prepared",
                            detail
                        );
                    }}
                />

                {#if $item.system.level > 0}
                    <Checkbox
                        label="A5E.SpellRitual"
                        checked={$item.system.ritual}
                        on:updateSelection={({ detail }) => {
                            updateDocumentDataFromField(
                                $item,
                                "system.ritual",
                                detail
                            );
                        }}
                    />
                {/if}
            </FormSection>
        </div>
    {:else}
        <FormSection>
            <dl class="summary-list">
                <div class="summary-list__item">
                    <dt class="summary-list__label">
                        {localize("A5E.SpellLevel")}:
                    </dt>

                    <dd class="summary-list__value">
                        {spellLevels[$item.system.level]}
                    </dd>
                </div>

                <div class="summary-list__item">
                    <dt class="summary-list__label">
                        {localize("A5E.SpellSchoolPrimary")}:
                    </dt>

                    <dd class="summary-list__value">
                        {spellSchools.primary[$item.system.schools.primary]}
                    </dd>
                </div>

                <div class="summary-list__item">
                    <dt class="summary-list__label">
                        {localize("A5E.SpellSchoolSecondaryPlural")}:
                    </dt>

                    <dd class="summary-list__value">
                        {selectedSecondarySpellSchools || localize("A5E.None")}
                    </dd>
                </div>

                <hr class="a5e-rule u-my-sm" />

                <div class="summary-list__item">
                    <dt class="summary-list__label">
                        {localize("A5E.SpellComponents")}:
                    </dt>

                    <dd class="summary-list__value">
                        {selectedSpellComponents || localize("A5E.None")}
                    </dd>
                </div>

                {#if $item.system.components.material && $item.system.materials}
                    <div class="summary-list__item">
                        <dt class="summary-list__label">
                            {localize("A5E.SpellMaterials")}:
                        </dt>

                        <dd class="summary-list__value">
                            {$item.system.materials}
                        </dd>
                    </div>
                {/if}
            </dl>
        </FormSection>
    {/if}
</section>

<style lang="scss">
    .summary-list {
        display: flex;
        flex-direction: column;
        gap: 0.375rem;
        margin: 0;
        font-size: $font-size-sm;

        &__item {
            display: flex;
            align-items: flex-start;
        }

        &__label {
            font-weight: bold;
            white-space: nowrap;
        }

        &__value {
            margin: 0;
        }
    }
</style>

// src/vue/sheets/pages/partials/SpellConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Spell Properties</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.SpellLevel">
        <radio-group
          :document="item"
          :options="Object.entries(config.spellLevels)"
          updatePath="data.level"
        />
      </form-section>

      <form-section heading="A5E.SpellSchoolPrimary">
        <radio-group
          :document="item"
          :options="Object.entries(config.spellSchools.primary)"
          updatePath="data.schools.primary"
        />
      </form-section>

      <form-section heading="A5E.SpellSchoolSecondaryPlural">
        <checkbox-group
          :document="item"
          :options="Object.entries(config.spellSchools.secondary)"
          updatePath="data.schools.secondary"
        />
      </form-section>

      <form-section heading="A5E.SpellComponents">
        <ul
          class="
            u-flex
            u-flex-wrap
            u-gap-sm
            u-list-style-none
            u-m-0
            u-p-0
            u-text-xs
            u-w-full
          "
        >
          <option-tag
            v-for="[value, label] in Object.entries(config.spellComponents)"
            :key="value"
            v-bind="{ label, value }"
            :selected="data.data.components[value]"
            @option-selected="onUpdateSpellComponentSelection"
          />
        </ul>
      </form-section>

      <form-section
        v-if="data.data.components.material"
        heading="A5E.SpellMaterials"
      >
        <div class="u-w-full">
          <input
            class="a5e-input"
            name="data.materials"
            type="text"
            :value="data.data.materials"
          />
        </div>
      </form-section>

      <form-section>
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.concentration"
              :id="`${appId}-concentration`"
              :checked="data.data.concentration"
            />

            <label class="u-pointer" :for="`${appId}-concentration`">
              {{ localize("A5E.SpellConcentration") }}
            </label>
          </div>

          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.prepared"
              :id="`${appId}-prepared`"
              :checked="data.data.prepared"
            />

            <label class="u-pointer" :for="`${appId}-prepared`">
              {{ localize("A5E.ItemPrepared") }}
            </label>
          </div>

          <div
            v-if="data.data.level > 0"
            class="u-align-center u-flex u-gap-md"
          >
            <input
              class="u-pointer"
              type="checkbox"
              name="data.ritual"
              :id="`${appId}-ritual`"
              :checked="data.data.ritual"
            />

            <label class="u-pointer" :for="`${appId}-ritual`">
              {{ localize("A5E.SpellRitual") }}
            </label>
          </div>
        </div>
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellLevel") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ localize(config.spellLevels[data.data.level]) }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellSchoolPrimary") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ localize(config.spellSchools.primary[data.data.schools.primary]) }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.SpellSchoolSecondaryPlural") }}:
        </dt>

        <dd class="u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-wrap
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
            "
            v-if="data.data.schools.secondary.length"
          >
            <li v-for="school in data.data.schools.secondary" :key="school">
              {{ localize(config.spellSchools.secondary[school] ?? school) }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>

      <hr class="a5e-rule u-my-sm" />

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellComponents") }}:</dt>
        <dd class="u-flex u-gap-ch u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-shrink-0
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
              u-w-fit
            "
            v-if="Object.values(data.data.components).some(Boolean)"
          >
            <li
              v-for="[component] in Object.entries(data.data.components).filter(
                ([_, state]) => state
              )"
              :key="component"
            >
              {{
                localize(
                  `${config.spellComponents[component]}Abbr` ?? component
                )
              }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>

      <div
        v-if="data.data.components.material && data.data.materials"
        class="u-flex u-gap-md"
      >
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.SpellMaterials") }}:
        </dt>

        <dd class="u-m-0 u-p-0">
          {{ data.data.materials }}
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { computed, inject, ref, watch } from "vue";

import CheckboxGroup from "../../../forms/CheckboxGroup.vue";
import FormSection from "../../../forms/FormSection.vue";
import OptionTag from "../../../forms/OptionTag.vue";
import RadioGroup from "../../../forms/RadioGroup.vue";

export default {
  components: { CheckboxGroup, FormSection, OptionTag, RadioGroup },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    watch(
      () => data.value.data.level,
      (level) => {
        if (parseInt(level, 10) === 0) {
          item.update({ "data.ritual": false });
        }
      }
    );

    function onUpdateSpellComponentSelection(key) {
      item.update({
        [`data.components.${key}`]: !data.value.data.components[key],
      });
    }

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
      onUpdateSpellComponentSelection,
    };
  },
};
</script>
