// src/apps/components/RadioGroup.svelte
<script>
    import { createEventDispatcher } from "svelte";

    import Tag from "./Tag.svelte";

    export let listClasses = "";
    export let optionStyles = "";
    export let options = [];
    export let selected = "";

    const dispatch = createEventDispatcher();

    function updateSelection(value) {
        dispatch("updateSelection", value === selected ? "" : value);
    }
</script>

<ul
    class="
        u-flex
        u-flex-wrap
        u-gap-sm
        u-list-style-none
        u-m-0
        u-p-0
        u-text-xs
        u-w-full
        {listClasses}
    "
>
    {#each options as [value, label]}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <Tag
            active={selected === value || selected?.toString() === value}
            {optionStyles}
            {value}
            {label}
            on:tagToggle={({ detail }) => updateSelection(detail)}
        />
    {/each}
</ul>

// src/vue/forms/RadioGroup.vue
<template>
  <ul
    class="
      u-flex
      u-flex-wrap
      u-gap-sm
      u-list-style-none
      u-m-0
      u-p-0
      u-text-xs
      u-w-full
    "
    :class="listClasses"
  >
    <option-tag
      v-for="[value, label] in options"
      :key="value"
      v-bind="{ classes: optionClasses, label, value }"
      :selected="selected === value || selected?.toString() === value"
      @option-selected="onOptionSelected"
    />
  </ul>
</template>

<script>
import OptionTag from "./OptionTag.vue";

export default {
  components: { OptionTag },
  props: {
    listClasses: { type: String, default: "" },
    optionClasses: { type: String, default: "" },
    options: Array,
    selected: String | Number,
    selectionHandler: Function,
  },
  setup(props) {
    function onOptionSelected(option) {
      props.selectionHandler(option);
    }

    return {
      onOptionSelected,
    };
  },
};
</script>
