// src/vue/sheets/header/partials/AbilityScore.vue
<template>
  <li
    class="
      u-align-center
      u-bg-gray
      u-flex
      u-flex-col
      u-font-serif
      u-py-xs
      u-rounded
      u-w-full
    "
  >
    <h4 class="u-text-lg">{{ ability.label }}</h4>

    <div v-if="sheetIsLocked" class="a5e-ability-score__value">
      {{ ability.value }}
    </div>

    <input
      v-else
      class="a5e-ability-score__value"
      :name="`data.abilities.${label}.value`"
      type="number"
      :value="ability.value"
      placeholder="10"
    />

    <div
      class="a5e-ability-score__buttons"
      :class="{ 'u-justify-center u-gap-lg': sheetIsLocked }"
    >
      <div
        class="a5e-ability-score__roll-button"
        :title="localize('A5E.RollAbilityCheck')"
        @click="onRollAbilityCheck(label)"
      >
        {{ ability.check.deterministicBonus }}

        <div class="a5e-tooltip a5e-tooltip--ability-score">
          {{ localize("A5E.RollAbilityCheck") }}
        </div>
      </div>

      <i
        v-if="!sheetIsLocked"
        class="a5e-config-button fas fa-cog"
        :title="localize('A5E.ConfigureBonuses')"
        @click="onClickConfigButton(label)"
      ></i>

      <div
        class="a5e-ability-score__roll-button a5e-js-roll-saving-throw"
        :title="localize('A5E.RollSavingThrow')"
        @click="onRollSavingThrow(label)"
      >
        {{ ability.save.deterministicBonus }}

        <div
          class="a5e-tooltip a5e-tooltip--ability-score"
          :class="{ 'a5e-tooltip--obstacle-right': label === 'cha' }"
        >
          {{ localize("A5E.RollSavingThrow") }}
        </div>
      </div>
    </div>
  </li>
</template>

<script>
import { inject } from "vue";

export default {
  props: { ability: Object, label: String, sheetIsLocked: Boolean },
  setup() {
    const actor = inject("actor");

    function onClickConfigButton(ability) {
      actor.configureAbilityScore(ability);
    }

    function onRollAbilityCheck(ability) {
      actor.rollAbilityCheck(ability);
    }

    function onRollSavingThrow(ability) {
      actor.rollSavingThrow(ability);
    }

    return {
      localize: (key) => game.i18n.localize(key),
      onClickConfigButton,
      onRollAbilityCheck,
      onRollSavingThrow,
    };
  },
};
</script>

// src/apps/components/ActorSheetHeader/AbilityScore.svelte
<script>
    import { getContext } from "svelte";
    import { localize } from "@typhonjs-fvtt/runtime/svelte/helper";

    import pressedKeysStore from "../../../stores/pressedKeysStore";

    import getKeyPressAsOptions from "../../handlers/getKeyPressAsOptions";
    import updateDocumentDataFromField from "../../utils/updateDocumentDataFromField";

    export let ability;
    export let abilityLabel;

    const actor = getContext("actor");

    $: sheetIsLocked = !$actor.isOwner
        ? true
        : $actor.flags?.a5e?.sheetIsLocked ?? true;
</script>

<li class="ability-score">
    <div class="ability-score__main">
        <h3>{localize(abilityLabel)}</h3>

        <input
            class="ability-score__value"
            name="system.abilities.{abilityLabel}.value"
            type="number"
            value={ability.value}
            on:change={({ target }) =>
                updateDocumentDataFromField(
                    $actor,
                    target.name,
                    Number(target.value)
                )}
            placeholder="10"
            disabled={sheetIsLocked}
        />
    </div>

    <button
        class="roll-button"
        data-tooltip="A5E.RollAbilityCheck"
        data-tooltip-direction="DOWN"
        on:click={() =>
            $actor.rollAbilityCheck(
                abilityLabel,
                getKeyPressAsOptions($pressedKeysStore)
            )}
    >
        <h4 class="roll-button__label">Check</h4>

        <div class="roll-button__value">
            {ability.check.deterministicBonus}
        </div>
    </button>

    <button
        class="roll-button"
        data-tooltip="A5E.RollSavingThrow"
        data-tooltip-direction="DOWN"
        on:click={() =>
            $actor.rollSavingThrow(
                abilityLabel,
                getKeyPressAsOptions($pressedKeysStore)
            )}
    >
        <h4 class="roll-button__label">Save</h4>

        <div class="roll-button__value">
            {ability.save.deterministicBonus}
        </div>
    </button>

    {#if !(!$actor.isOwner ? true : $actor.flags?.a5e?.sheetIsLocked ?? true)}
        <button
            on:click={() =>
                $actor.configureAbilityScore({ abilityKey: abilityLabel })}
            class="fas fa-gear a5e-button--edit-config"
        />
    {/if}
</li>

<style lang="scss">
    .ability-score {
        position: relative;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        align-items: center;
        width: 100%;
        color: #f6f2eb;
        font-family: "Modesto Condensed", serif;
        border-radius: 3px;
        gap: 0.25rem;
        overflow: hidden;

        &__main {
            grid-column: span 2;
        }

        &__value {
            display: flex;
            align-items: center;
            height: 26px;
            border: 0;
            color: #191813;
            margin-bottom: 0;
            background: none;
            font-size: 1.44rem;
            font-weight: inherit;
            text-align: center;

            &:focus {
                box-shadow: none;
            }

            &::placeholder {
                color: lighten(#191813, 35%);
            }
        }
    }

    .ability-score__main,
    .roll-button {
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        width: 100%;
        padding: 0.125rem 0;
        margin: 0;
        font-family: "Modesto Condensed", serif;
        color: #7e7960;
        border: 1px solid #ccc;
        border-radius: 4px;
        background: #f6f2eb;
        box-shadow: 0 0 5px #ccc inset;
        line-height: unset;
    }

    .roll-button {
        cursor: pointer;

        &__label {
            font-size: 0.694rem;
        }

        &__value {
            color: #191813;
        }
    }

    .a5e-button--edit-config {
        top: 0.25rem;
        right: 0.25rem;
    }
</style>
