// src/vue/sheets/header/partials/ArmorClass.vue
<template>
  <li
    class="
      u-align-center
      u-bg-gray
      u-flex
      u-flex-col
      u-justify-space-between
      u-py-xs
      u-rounded
      u-w-full
    "
  >
    <h4 class="u-text-lg">{{ localize("A5E.ArmorClassAbbr") }}</h4>

    <div
      v-if="sheetIsLocked"
      class="a5e-ability-score__value a5e-ability-score__value--ac"
    >
      {{ data.data.attributes.ac }}
    </div>

    <input
      v-else
      class="a5e-ability-score__value a5e-ability-score__value--ac"
      name="data.attributes.ac"
      type="number"
      :value="data.data.attributes.ac"
      placeholder="10"
      data-dtype="Number"
    />
  </li>
</template>

<script>
import { inject } from "vue";

export default {
  props: { sheetIsLocked: Boolean },
  setup() {
    const data = inject("data");
    return {
      data,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>

// src/apps/components/ActorSheetHeader/ArmorClass.svelte
<script>
    import { getContext } from "svelte";

    import updateDocumentDataFromField from "../../utils/updateDocumentDataFromField";

    const actor = getContext("actor");
</script>

<!-- <div
        v-if="sheetIsLocked"
        class="a5e-ability-score__value a5e-ability-score__value--ac"
    >
        {$actor.system.attributes.ac}
    </div> -->

<input
    class="ac-value"
    name="system.attributes.ac"
    type="number"
    value={$actor.system.attributes.ac}
    placeholder="10"
    on:change={({ target }) =>
        updateDocumentDataFromField($actor, target.name, Number(target.value))}
/>

<style lang="scss">
    .ac-value,
    .ac-value[type="number"] {
        display: flex;
        align-items: center;
        height: 26px;
        border: 0;
        background: none;
        font-weight: inherit;
        text-align: center;
        margin-bottom: 1rem;
        font-size: 1.728rem;
    }
</style>
