// src/vue/sheets/pages/partials/config/ArmorConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Armor Configuration</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.ArmorCategory">
        <update-wrapper
          :document="item"
          updatePath="data.armorCategory"
          v-slot="slotProps"
        >
          <radio-group
            :options="
              Object.entries(config.armor).filter(
                ([key, _]) => key !== 'shield'
              )
            "
            :selected="data.data.armorCategory"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section heading="A5E.ArmorProperties">
        <update-wrapper
          :document="item"
          updatePath="data.armorProperties"
          v-slot="slotProps"
        >
          <checkbox-group
            :options="Object.entries(config.armorProperties)"
            :selected="data.data.armorProperties"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ArmorCategory") }}:</dt>
        <dd class="u-m-0 u-p-0">
          <template v-if="data.data.armorCategory">
            {{
              localize(
                config.armor[data.data.armorCategory] ?? data.data.armorCategory
              )
            }}
          </template>

          <template v-else>
            {{ localize("A5E.Unknown") }}
          </template>
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.ArmorProperties") }}:
        </dt>
        <dd class="u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-wrap
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
            "
            v-if="data.data.armorProperties.length"
          >
            <li
              v-for="property in data.data.armorProperties.sort((a, b) =>
                a.toLowerCase().localeCompare(b.toLowerCase())
              )"
              :key="property"
            >
              {{ localize(config.armorProperties[property] ?? property) }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { inject, ref } from "vue";

import CheckboxGroup from "../../../../forms/CheckboxGroup.vue";
import FormSection from "../../../../forms/FormSection.vue";
import RadioGroup from "../../../../forms/RadioGroup.vue";
import UpdateWrapper from "../../../../forms/UpdateWrapper.vue";

export default {
  components: { CheckboxGroup, FormSection, RadioGroup, UpdateWrapper },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>

// src/apps/components/itemPropertiesConfig/ArmorConfiguration.svelte
<script>
    import { getContext } from "svelte";
    import { localize } from "@typhonjs-fvtt/runtime/svelte/helper";

    import FormSection from "../FormSection.svelte";
    import CheckboxGroup from "../CheckboxGroup.svelte";
    import RadioGroup from "../RadioGroup.svelte";

    const item = getContext("item");

    let editMode = false;

    function toggleEditMode() {
        editMode = !editMode;
    }

    const armorProperties = CONFIG.A5E.armorProperties;
</script>

<section>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <header
        class="
            u-align-center
            u-flex
            u-font-serif
            u-gap-md
            u-mb-lg
            u-ml-xs
            u-pointer
            u-text-lg
            u-w-fit
        "
        on:click={toggleEditMode}
    >
        <h3>{localize("Armor Configuration")}</h3>
        <i
            class="u-text-sm fas"
            class:fa-chevron-up={editMode}
            class:fa-edit={!editMode}
        />
    </header>

    {#if editMode}
        <div class="u-flex u-flex-col u-gap-md">
            <FormSection heading="A5E.ArmorCategory">
                <!-- svelte-ignore missing-declaration -->
                <RadioGroup
                    options={Object.entries(CONFIG.A5E.armor)}
                    selected={$item.system.armorCategory}
                    name="system.armorCategory"
                    document={item}
                />
            </FormSection>

            <FormSection heading="A5E.ArmorProperties">
                <!-- svelte-ignore missing-declaration -->
                <CheckboxGroup
                    options={Object.entries(armorProperties)}
                    selected={$item.system.armorProperties}
                    name="system.armorProperties"
                />
            </FormSection>
        </div>
    {:else}
        <dl class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm">
            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ArmorCategory")}:</dt>
                <dd class="u-m-0 u-p-0">
                    <!-- svelte-ignore missing-declaration -->
                    {#if $item.system.armorCategory}
                        {localize(
                            CONFIG.A5E.armor[$item.system.armorCategory] ??
                                $item.system.armorCategory
                        )}
                    {:else}
                        {localize("A5E.Unknown")}
                    {/if}
                </dd>
            </div>

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ArmorProperties")}:</dt>
                <dd class="u-m-0 u-p-0">
                    {#if $item.system.armorProperties.length}
                        <ul
                            class="
              u-comma-list
              u-flex
              u-flex-shrink-0
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
              u-w-fit
            "
                        >
                            {#each $item.system.armorProperties.sort((a, b) => a
                                    .toLowerCase()
                                    .localeCompare(b.toLowerCase())) as property}
                                <li key={property}>
                                    {localize(
                                        armorProperties[property] ?? property
                                    )}
                                </li>
                            {/each}
                        </ul>
                    {:else}
                        {localize("A5E.None")}
                    {/if}
                </dd>
            </div>
        </dl>
    {/if}
</section>
