// src/vue/forms/CheckboxGroup.vue
<template>
  <ul
    class="
      u-flex
      u-flex-wrap
      u-gap-sm
      u-list-style-none
      u-m-0
      u-p-0
      u-text-xs
      u-w-full
    "
  >
    <option-tag
      v-for="[value, label] in options"
      :key="value"
      v-bind="{ label, value }"
      :selected="selected.includes(value)"
      @option-selected="onOptionSelected"
    />
  </ul>
</template>

<script>
import { computed, inject } from "vue";

import OptionTag from "./OptionTag.vue";

export default {
  components: { OptionTag },
  props: {
    document: Object,
    options: Array,
    updatePath: [String, Array],
  },
  setup(props) {
    const data = inject("data");

    const selected = computed(() => {
      return getProperty(data.value, props.updatePath);
    });

    function onOptionSelected(option) {
      const currentSelection = Array.from(selected.value);
      const index = currentSelection.indexOf(option);

      if (index !== -1) currentSelection.splice(index, 1);
      else currentSelection.push(option);

      props.document.update({ [props.updatePath]: currentSelection });
    }

    return {
      data,
      onOptionSelected,
      selected,
    };
  },
};
</script>

// src/apps/components/itemPropertiesConfig/CheckboxGroup.svelte
<script>
  import { getContext } from "svelte";
  import { localize } from "@typhonjs-fvtt/runtime/svelte/helper";

  import updateDocumentDataFromField from "../../utils/updateDocumentDataFromField";

  export let options = [];
  export let selected = [];
  export let name;

  const item = getContext("item");

  function update(value) {
    const temp = new Set(selected);

    if (temp.has(value)) temp.delete(value);
    else temp.add(value);

    updateDocumentDataFromField($item, name, [...temp]);
  }
</script>

<ul
  class="
        u-flex
        u-flex-wrap
        u-gap-sm
        u-list-style-none
        u-m-0
        u-p-0
        u-text-xs
        u-w-full
    "
>
  {#each options as [value, label]}
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <li
      class="a5e-tag u-pointer"
      class:a5e-tag--inactive={!selected.includes(value)}
      on:click={() => update(value)}
    >
      {localize(label)}
    </li>
  {/each}
</ul>
