// src/vue/sheets/pages/partials/config/ObjectConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Object Properties</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.ObjectTypePrompt">
        <radio-group
          :document="item"
          :options="Object.entries(config.objectTypes)"
          updatePath="data.objectType"
        />
      </form-section>

      <form-section heading="A5E.ItemRarity">
        <radio-group
          :document="item"
          :options="Object.entries(config.itemRarity)"
          updatePath="data.rarity"
        />
      </form-section>

      <form-section>
        <div class="u-flex u-gap-xxxl u-text-sm u-w-full">
          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.requiresAttunement"
              :id="`${appId}-attunement-required`"
              :checked="data.data.requiresAttunement"
            />

            <label class="u-pointer" :for="`${appId}-attunement-required`">
              {{ localize("A5E.AttunementRequiredPrompt") }}
            </label>
          </div>

          <div
            v-if="data.data.requiresAttunement"
            class="u-align-center u-flex u-gap-md"
          >
            <input
              class="u-pointer"
              type="checkbox"
              name="data.attuned"
              :id="`${appId}-attuned`"
              :checked="data.data.attuned"
            />

            <label class="u-pointer" :for="`${appId}-attuned`">
              {{ localize("A5E.AttunementPrompt") }}
            </label>
          </div>

          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.plotItem"
              :id="`${appId}-plot-item`"
              :checked="data.data.plotItem"
            />

            <label class="u-pointer" :for="`${appId}-plot-item`">
              {{ localize("A5E.PlotItem") }}
            </label>
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemWeight">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="align-center u-flex u-gap-xxl">
            <div class="u-w-30">
              <input
                type="text"
                name="data.weight"
                :id="`${appId}-weight`"
                :value="data.data.weight"
              />
            </div>

            <div class="u-align-center u-flex u-gap-md">
              <input
                class="u-pointer"
                type="checkbox"
                name="data.bulky"
                :id="`${appId}-bulky`"
                :checked="data.data.bulky"
              />

              <label class="u-pointer" :for="`${appId}-bulky`">
                {{ localize("A5E.ItemBulky") }}
              </label>
            </div>

            <div class="u-align-center u-flex u-gap-md">
              <input
                class="u-pointer"
                type="checkbox"
                name="data.equipped"
                :id="`${appId}-equipped`"
                :checked="data.data.equipped"
              />

              <label class="u-pointer" :for="`${appId}-equipped`">
                {{ localize("A5E.ItemEquipped") }}
              </label>
            </div>
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemQuantity">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-w-20">
            <input
              type="number"
              data-dtype="Number"
              name="data.quantity"
              :id="`${appId}-quantity`"
              :value="data.data.quantity"
            />
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemPrice">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-w-30">
            <input
              class="u-pl-lg"
              type="text"
              data-dtype="String"
              name="data.price"
              :id="`${appId}-price`"
              :value="data.data.price"
            />
          </div>
        </div>
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ObjectTypePrompt") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{
            localize(
              config.objectTypes[data.data.objectType] ?? data.data.objectType
            )
          }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemRarity") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{
            localize(config.itemRarity[data.data.rarity] ?? data.data.rarity)
          }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.Attunement") }}:</dt>
        <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
          <template v-if="data.data.requiresAttunement">
            {{ localize("A5E.AttunementRequired") }}

            ({{
              localize(data.data.attuned ? "A5E.Attuned" : "A5E.AttunedNot")
            }})
          </template>

          <template v-else>
            {{ localize("A5E.AttunementNotRequired") }}
          </template>
        </dd>
      </div>

      <hr class="a5e-rule u-my-sm" />

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemWeight") }}:</dt>
        <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
          {{ data.data.weight }}

          <template v-if="data.data.bulky">
            ({{ localize("A5E.ItemBulky") }})
          </template>
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemQuantity") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ data.data.quantity || 0 }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemPrice") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ data.data.price || 0 }}
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { inject, ref } from "vue";

import FormSection from "../../../../forms/FormSection.vue";
import RadioGroup from "../../../../forms/RadioGroup.vue";

export default {
  components: { FormSection, RadioGroup },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>

// src/apps/components/itemPropertiesConfig/ObjectConfiguration.svelte
<script>
    import { getContext } from "svelte";
    import { localize } from "@typhonjs-fvtt/runtime/svelte/helper";

    import Checkbox from "../Checkbox.svelte";
    import FormSection from "../FormSection.svelte";
    import RadioGroup from "../RadioGroup.svelte";
    import updateDocumentDataFromField from "../../../utils/updateDocumentDataFromField";

    const item = getContext("item");
    const appId = getContext("appId");
    const { A5E } = CONFIG;
    const { isGM } = game.user;

    let editMode = false;
</script>

<section>
    <!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
    <header
        class="
            u-align-center
            u-flex
            u-font-serif
            u-gap-md
            u-mb-lg
            u-ml-xs
            u-pointer
            u-text-lg
            u-w-fit
        "
        on:click={() => (editMode = !editMode)}
    >
        <h3>{localize("A5E.TabObjectProperties")}</h3>
        <i
            class="u-text-sm fas"
            class:fa-chevron-up={editMode}
            class:fa-edit={!editMode}
        />
    </header>

    {#if editMode}
        <div class="u-flex u-flex-col u-gap-md">
            <FormSection heading="A5E.ObjectTypePrompt">
                <RadioGroup
                    options={Object.entries(A5E.objectTypes)}
                    selected={$item.system.objectType}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.objectType",
                            event.detail
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.ItemRarity">
                <RadioGroup
                    options={Object.entries(A5E.itemRarity)}
                    selected={$item.system.rarity}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.rarity",
                            event.detail
                        )}
                />
            </FormSection>

            <FormSection --gap="0.5rem 1.25rem">
                <Checkbox
                    label="A5E.AttunementRequiredPrompt"
                    checked={$item.system.requiresAttunement}
                    on:updateSelection={({ detail }) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.requiresAttunement",
                            detail
                        )}
                />

                {#if $item.actor && $item.system.requiresAttunement}
                    <Checkbox
                        label="A5E.AttunementPrompt"
                        checked={$item.system.attuned}
                        on:updateSelection={({ detail }) =>
                            updateDocumentDataFromField(
                                $item,
                                "system.attuned",
                                detail
                            )}
                    />
                {/if}
                {#if isGM}
                    <Checkbox
                        label="A5E.PlotItem"
                        checked={$item.system.plotItem}
                        on:updateSelection={({ detail }) =>
                            updateDocumentDataFromField(
                                $item,
                                "system.plotItem",
                                detail
                            )}
                    />

                    <Checkbox
                        label="A5E.ItemUnidentified"
                        checked={$item.system.unidentified}
                        on:updateSelection={({ detail }) =>
                            updateDocumentDataFromField(
                                $item,
                                "system.unidentified",
                                detail
                            )}
                    />
                {/if}
            </FormSection>

            <FormSection
                heading="A5E.ItemWeight"
                --label-width="100%"
                --gap="0.375rem 1.25rem"
            >
                <div class="u-align-center u-flex u-gap-md u-w-30">
                    <input
                        type="number"
                        data-dtype="Number"
                        name="system.weight"
                        id="{appId}-weight"
                        value={$item.system.weight}
                        on:change={({ target }) =>
                            updateDocumentDataFromField(
                                $item,
                                target.name,
                                Number(target.value)
                            )}
                    />

                    <label class="u-pointer" for="{appId}-weight">
                        {localize("A5E.DetailsWeightLbs")}
                    </label>
                </div>

                <Checkbox
                    label="A5E.ItemBulky"
                    checked={$item.system.bulky}
                    on:updateSelection={({ detail }) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.bulky",
                            detail
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.ItemEquippedState" --label-width="100%">
                <RadioGroup
                    options={Object.entries(A5E.equippedStates)}
                    selected={$item.system.equippedState}
                    on:updateSelection={({ detail }) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.equippedState",
                            parseInt(detail, 10)
                        )}
                />
            </FormSection>

            <FormSection heading="A5E.ItemQuantity">
                <div
                    class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
                >
                    <div class="u-w-20">
                        <input
                            type="number"
                            data-dtype="Number"
                            min="0"
                            max="9999"
                            name="system.quantity"
                            id={`${appId}-quantity`}
                            value={$item.system.quantity}
                            on:change={({ target }) =>
                                updateDocumentDataFromField(
                                    $item,
                                    target.name,
                                    Number(target.value)
                                )}
                        />
                    </div>
                </div>
            </FormSection>

            <FormSection heading="A5E.ItemPrice">
                <div
                    class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
                >
                    <div class="u-align-center u-flex u-gap-md u-w-30">
                        <input
                            class="u-pl-lg"
                            type="text"
                            name="system.price"
                            id={`${appId}-price`}
                            value={$item.system.price}
                            on:change={({ target }) =>
                                updateDocumentDataFromField(
                                    $item,
                                    target.name,
                                    target.value
                                )}
                        />
                    </div>
                </div>
            </FormSection>

            <FormSection heading="A5E.CraftingComponents">
                <div
                    class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
                >
                    <div class="u-align-center u-flex u-gap-md u-w-full">
                        <input
                            class="u-pl-lg"
                            type="text"
                            name="system.craftingComponents"
                            value={$item.system.craftingComponents}
                            id={`${appId}-craftingComponents`}
                            on:change={({ target }) =>
                                updateDocumentDataFromField(
                                    $item,
                                    target.name,
                                    target.value
                                )}
                        />
                    </div>
                </div>
            </FormSection>

            <FormSection heading="A5E.ItemCondition" --direction="column">
                <RadioGroup
                    options={Object.entries(A5E.damagedStates)}
                    selected={$item.system.damagedState}
                    on:updateSelection={({ detail }) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.damagedState",
                            parseInt(detail, 10)
                        )}
                />
            </FormSection>
        </div>
    {:else}
        <dl class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm">
            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ObjectTypePrompt")}:</dt>
                <dd class="u-m-0 u-p-0">
                    {A5E.objectTypes[$item.system.objectType] ??
                        localize("A5E.None")}
                </dd>
            </div>

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ItemRarity")}:</dt>
                <dd class="u-m-0 u-p-0">
                    {localize(
                        A5E.itemRarity[$item.system.rarity] ??
                            $item.system.rarity
                    )}
                </dd>
            </div>

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.Attunement")}:</dt>
                <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
                    {#if $item.system.requiresAttunement}
                        {localize("A5E.AttunementRequired")}

                        ({localize(
                            $item.system.attuned
                                ? "A5E.Attuned"
                                : "A5E.AttunedNot"
                        )})
                    {:else}
                        {localize("A5E.AttunementNotRequired")}
                    {/if}
                </dd>
            </div>

            <hr class="a5e-rule u-my-sm" />

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ItemWeight")}:</dt>
                <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
                    {$item.system.weight}
                    {localize("A5E.DetailsWeightLbs")}

                    {#if $item.system.bulky}
                        ({localize("A5E.ItemBulky")})
                    {/if}
                </dd>
            </div>

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ItemQuantity")}:</dt>
                <dd class="u-m-0 u-p-0">
                    {$item.system.quantity || 0}
                </dd>
            </div>

            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">{localize("A5E.ItemPrice")}:</dt>
                <dd class="u-m-0 u-p-0">
                    {$item.system.price ?? localize("A5E.None")}
                </dd>
            </div>
            {#if $item.system.craftingComponents != ""}
                <div class="u-flex u-gap-md">
                    <dt class="u-text-bold">
                        {localize("A5E.CraftingComponents")}:
                    </dt>
                    <dd class="u-m-0 u-p-0">
                        {$item.system.craftingComponents ??
                            localize("A5E.None")}
                    </dd>
                </div>
            {/if}
        </dl>
    {/if}
</section>
