// src/vue/sheets/pages/partials/ManeuverConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Maneuver Properties</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.ManeuverDegreePrompt">
        <radio-group
          :document="item"
          :options="Object.entries(config.maneuverDegrees)"
          updatePath="data.degree"
        />
      </form-section>

      <template v-if="data.data.degree > 0">
        <form-section heading="A5E.ManeuverTraditionPrompt">
          <radio-group
            :document="item"
            :options="Object.entries(config.maneuverTraditions)"
            updatePath="data.tradition"
          />
        </form-section>

        <form-section>
          <div
            class="
              u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full
            "
          >
            <label class="u-text-bold u-w-full" :for="`${appId}-exertion-cost`">
              {{ localize("A5E.ItemExertionCost") }}
            </label>

            <div class="u-w-20">
              <input
                type="number"
                data-dtype="Number"
                name="data.exertionCost"
                :value="data.data.exertionCost"
                :id="`${appId}-exertion-cost`"
              />
            </div>
          </div>
        </form-section>
      </template>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ManeuverDegreePrompt") }}:</dt>

        <dd class="u-m-0 u-p-0">
          {{ localize(config.maneuverDegrees[data.data.degree]) }}
        </dd>
      </div>

      <template v-if="data.data.degree > 0">
        <div class="u-flex u-gap-md">
          <dt class="u-text-bold">
            {{ localize("A5E.ManeuverTraditionPrompt") }}:
          </dt>

          <dd class="u-m-0 u-p-0">
            {{
              localize(
                config.maneuverTraditions[data.data.tradition] ?? "A5E.None"
              )
            }}
          </dd>
        </div>

        <div class="u-flex u-gap-md">
          <dt class="u-text-bold">{{ localize("A5E.ItemExertionCost") }}:</dt>
          <dd class="u-m-0 u-p-0">{{ data.data.exertionCost || 0 }}</dd>
        </div>
      </template>
    </dl>
  </section>
</template>

<script>
import { computed, inject, ref } from "vue";

import FormSection from "../../../forms/FormSection.vue";
import RadioGroup from "../../../forms/RadioGroup.vue";

export default {
  components: { FormSection, RadioGroup },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>

// src/view/sheets/components/item/ManeuverConfiguration.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { localize } from "#utils/localization/localize.ts";

    import { objectEntriesNumberKeyConverter } from "#utils/objectEntriesNumberKeyConverter.ts";
    import updateDocumentDataFromField from "#utils/updateDocumentDataFromField.ts";

    import Checkbox from "#view/snippets/Checkbox.svelte";
    import FieldWrapper from "#view/snippets/FieldWrapper.svelte";
    import Section from "#view/snippets/Section.svelte";
    import RadioGroup from "#view/snippets/RadioGroup.svelte";

    let item: any = getContext("item");
    let itemStore = $derived(item.reactive.system);
    const { maneuverDegrees, maneuverTraditions } = CONFIG.A5E;

    let editMode = $state(false);
</script>

<Section
    heading="A5E.TabManeuverProperties"
    headerButtons={[
        {
            classes: `icon fa-solid ${editMode ? "fa-chevron-up" : "fa-edit"}`,
            handler: () => (editMode = !editMode),
        },
    ]}
    --a5e-section-body-gap="0.75rem"
    --a5e-section-heading-gap="0.5rem"
    --a5e-section-heading-template-columns="max-content max-content"
>
    {#if editMode}
        <RadioGroup
            heading="A5E.ManeuverDegreePrompt"
            options={objectEntriesNumberKeyConverter(maneuverDegrees)}
            selected={parseInt(itemStore.degree, 10)}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(item, "system.degree", value)}
        />

        {#if itemStore.degree > 0}
            <RadioGroup
                heading="A5E.ManeuverTraditionPrompt"
                options={Object.entries(maneuverTraditions)}
                selected={itemStore.tradition}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(
                        item,
                        "system.tradition",
                        value,
                    )}
            />

            <FieldWrapper>
                <Checkbox
                    label="A5E.ManeuverIsStance"
                    checked={itemStore.isStance}
                    onUpdateSelection={(value) => {
                        updateDocumentDataFromField(
                            item,
                            "system.isStance",
                            value,
                        );
                    }}
                />
            </FieldWrapper>

            <FieldWrapper>
                <Checkbox
                    label="A5E.SpellConcentration"
                    checked={itemStore.concentration}
                    onUpdateSelection={(value) => {
                        updateDocumentDataFromField(
                            item,
                            "system.concentration",
                            value,
                        );
                    }}
                />
            </FieldWrapper>

            <FieldWrapper heading="A5E.ItemExertionCost">
                <input
                    class="a5e-input a5e-input--slim a5e-input--small"
                    type="number"
                    name="system.exertionCost"
                    value={itemStore.exertionCost}
                    id="{item.uuid}-exertion-cost"
                    onchange={({ currentTarget }) =>
                        updateDocumentDataFromField(
                            item,
                            "system.exertionCost",
                            Number(currentTarget.value),
                        )}
                />
            </FieldWrapper>
        {/if}
    {:else}
        <dl class="a5e-dl-box">
            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ManeuverDegreePrompt")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {localize(maneuverDegrees[itemStore.degree])}

                    {#if itemStore.degree > 0 && itemStore.isStance}
                        {localize("A5E.ManeuverStance")}
                    {/if}
                </dd>
            </div>

            {#if itemStore.degree > 0}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.ManeuverTraditionPrompt")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {maneuverTraditions[itemStore.tradition] ??
                            localize("A5E.None")}
                    </dd>
                </div>

                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.ItemExertionCost")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {itemStore.exertionCost || "0"}
                    </dd>
                </div>
            {/if}
        </dl>
    {/if}
</Section>
