// src/vue/sheets/header/partials/AbilityScore.vue
<template>
  <li
    class="
      u-align-center
      u-bg-gray
      u-flex
      u-flex-col
      u-font-serif
      u-py-xs
      u-rounded
      u-w-full
    "
  >
    <h4 class="u-text-lg">{{ ability.label }}</h4>

    <div v-if="sheetIsLocked" class="a5e-ability-score__value">
      {{ ability.value }}
    </div>

    <input
      v-else
      class="a5e-ability-score__value"
      :name="`data.abilities.${label}.value`"
      type="number"
      :value="ability.value"
      placeholder="10"
    />

    <div
      class="a5e-ability-score__buttons"
      :class="{ 'u-justify-center u-gap-lg': sheetIsLocked }"
    >
      <div
        class="a5e-ability-score__roll-button"
        :title="localize('A5E.RollAbilityCheck')"
        @click="onRollAbilityCheck(label)"
      >
        {{ ability.check.deterministicBonus }}

        <div class="a5e-tooltip a5e-tooltip--ability-score">
          {{ localize("A5E.RollAbilityCheck") }}
        </div>
      </div>

      <i
        v-if="!sheetIsLocked"
        class="a5e-config-button fas fa-cog"
        :title="localize('A5E.ConfigureBonuses')"
        @click="onClickConfigButton(label)"
      ></i>

      <div
        class="a5e-ability-score__roll-button a5e-js-roll-saving-throw"
        :title="localize('A5E.RollSavingThrow')"
        @click="onRollSavingThrow(label)"
      >
        {{ ability.save.deterministicBonus }}

        <div
          class="a5e-tooltip a5e-tooltip--ability-score"
          :class="{ 'a5e-tooltip--obstacle-right': label === 'cha' }"
        >
          {{ localize("A5E.RollSavingThrow") }}
        </div>
      </div>
    </div>
  </li>
</template>

<script>
import { inject } from "vue";

export default {
  props: { ability: Object, label: String, sheetIsLocked: Boolean },
  setup() {
    const actor = inject("actor");

    function onClickConfigButton(ability) {
      actor.configureAbilityScore(ability);
    }

    function onRollAbilityCheck(ability) {
      actor.rollAbilityCheck(ability);
    }

    function onRollSavingThrow(ability) {
      actor.rollSavingThrow(ability);
    }

    return {
      localize: (key) => game.i18n.localize(key),
      onClickConfigButton,
      onRollAbilityCheck,
      onRollSavingThrow,
    };
  },
};
</script>

// src/view/sheets/components/AbilityScore.svelte
<script lang="ts">
    import { getContext } from "svelte";

    import { pressedKeys } from "#stores/pressedKeysStore.svelte.ts";

    import { replaceHyphenWithMinusSign } from "#utils/replaceHyphenWithMinusSign.ts";
    import updateDocumentDataFromField from "#utils/updateDocumentDataFromField.ts";
    import { getKeyPressAsOptions } from "#utils/view/getKeyPressAsOptions.ts";

    type Props = {
        ability: any;
        abilityKey: string;
        idx: number;
    };

    let actor: any = getContext("actor");
    let sheetIsLocked: () => boolean = getContext("sheetIsLocked");

    let { ability, abilityKey, idx }: Props = $props();

    function handleCheckClick(abilityKey: string) {
        if (!sheetIsLocked()) return;

        actor.rollAbilityCheck(abilityKey, getKeyPressAsOptions(pressedKeys));
    }

    function handleSaveClick(abilityKey: string) {
        if (!sheetIsLocked()) {
            const currentProficiencyState =
                actor.system.abilities[abilityKey]?.save?.proficient;

            actor.update({
                [`system.abilities.${abilityKey}.save.proficient`]:
                    !currentProficiencyState,
            });
        } else {
            actor.rollSavingThrow(
                abilityKey,
                getKeyPressAsOptions(pressedKeys),
            );
        }
    }

    let sourceValue = $derived(
        actor.reactive._source.system.abilities[abilityKey].value,
    );
</script>

<li class="a5e-ability-score">
    <header class="a5e-ability-score__header">
        <h3 class="a5e-ability-score__label">
            {abilityKey}
        </h3>

        {#if !(!actor.isOwner ? true : (sheetIsLocked() ?? true))}
            <button
                class="a5e-button a5e-button--config a5e-ability-score__config-button"
                aria-labelledby="Configure Ability Score"
                onclick={() => actor.configureAbilityScore({ abilityKey })}
            >
                <i class="fas fa-cog"></i>
            </button>
        {/if}
    </header>

    <div class="a5e-ability-score__body">
        <input
            class="a5e-ability-score__value"
            name="system.abilities.${abilityKey}.value"
            type="number"
            value={sheetIsLocked() ? ability.value : sourceValue}
            placeholder="10"
            disabled={sheetIsLocked()}
            onchange={({ target }) =>
                updateDocumentDataFromField(
                    actor,
                    // @ts-ignore
                    target.name,
                    // @ts-ignore
                    Number(target.value),
                )}
        />

        <button
            class="a5e-ability-score__roll-button a5e-ability-score__roll-button--check"
            class:a5e-ability-score__roll-button--no-click={!sheetIsLocked()}
            data-tooltip={sheetIsLocked() ? "A5E.RollAbilityCheck" : null}
            data-tooltip-direction="DOWN"
            onclick={() => handleCheckClick(abilityKey)}
        >
            <div class="a5e-ability-score__roll-button-value">
                {replaceHyphenWithMinusSign(ability.check.deterministicBonus)}
            </div>
        </button>

        <button
            class="a5e-ability-score__roll-button a5e-ability-score__roll-button--save"
            class:a5e-ability-score__roll-button--proficient={ability.save
                .proficient}
            data-tooltip={sheetIsLocked()
                ? "A5E.RollSavingThrow"
                : "Toggle Saving Throw Proficiency"}
            data-tooltip-direction="DOWN"
            onclick={() => handleSaveClick(abilityKey)}
        >
            <div class="a5e-ability-score__roll-button-value">
                {replaceHyphenWithMinusSign(ability.save.deterministicBonus)}
            </div>
        </button>
    </div>
</li>
