// src/apps/components/itemPropertiesConfig/AmmunitionConfiguration.svelte
<script>
    import { getContext } from "svelte";
    import { localize } from "@typhonjs-fvtt/runtime/svelte/helper";

    import localeSort from "../../../utils/localeSort";
    import updateDocumentDataFromField from "../../utils/updateDocumentDataFromField";

    import FormSection from "../FormSection.svelte";
    import CheckboxGroup from "../CheckboxGroup.svelte";

    const item = getContext("item");

    let editMode = false;

    function toggleEditMode() {
        editMode = !editMode;
    }

    const ammunitionProperties = CONFIG.A5E.ammunitionProperties;
</script>

<section>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <header
        class="
            u-align-center
            u-flex
            u-font-serif
            u-gap-md
            u-mb-lg
            u-ml-xs
            u-pointer
            u-text-lg
            u-w-fit
        "
        on:click={toggleEditMode}
    >
        <h3>{localize("Ammunition Configuration")}</h3>
        <i
            class="u-text-sm fas"
            class:fa-chevron-up={editMode}
            class:fa-edit={!editMode}
        />
    </header>

    {#if editMode}
        <div class="u-flex u-flex-col u-gap-md">
            <FormSection heading="A5E.AmmunitionProperties">
                <CheckboxGroup
                    options={Object.entries(ammunitionProperties)}
                    selected={$item.system.ammunitionProperties}
                    on:updateSelection={(event) =>
                        updateDocumentDataFromField(
                            $item,
                            "system.ammunitionProperties",
                            event.detail
                        )}
                />
            </FormSection>
        </div>
    {:else}
        <dl class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm">
            <div class="u-flex u-gap-md">
                <dt class="u-text-bold">
                    {localize("A5E.AmmunitionProperties")}:
                </dt>
                <dd class="u-m-0 u-p-0">
                    {#if $item.system.ammunitionProperties.length}
                        <ul
                            class="
                                u-comma-list
                                u-flex
                                u-flex-shrink-0
                                u-gap-ch
                                u-list-style-none
                                u-m-0
                                u-p-0
                                u-w-fit
                            "
                        >
                            {#each localeSort($item.system.ammunitionProperties) as property}
                                <li key={property}>
                                    {ammunitionProperties[property] ?? property}
                                </li>
                            {/each}
                        </ul>
                    {:else}
                        {localize("A5E.None")}
                    {/if}
                </dd>
            </div>
        </dl>
    {/if}
</section>

// src/vue/sheets/pages/partials/config/AmmunitionConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Ammunition Configuration</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.AmmunitionProperties">
        <checkbox-group
          :document="item"
          :options="Object.entries(config.ammunitionProperties)"
          updatePath="data.ammunitionProperties"
        />
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.AmmunitionProperties") }}:
        </dt>
        <dd class="u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-wrap
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
            "
            v-if="data.data.ammunitionProperties.length"
          >
            <li
              v-for="property in data.data.ammunitionProperties"
              :key="property"
            >
              {{ localize(config.ammunitionProperties[property] ?? property) }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { inject, ref } from "vue";

import CheckboxGroup from "../../../../forms/CheckboxGroup.vue";
import FormSection from "../../../../forms/FormSection.vue";

export default {
  components: { CheckboxGroup, FormSection },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>
