// src/view/sheets/components/item/ObjectConfiguration.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { localize } from "#utils/localization/localize.ts";

    import updateDocumentDataFromField from "#utils/updateDocumentDataFromField.ts";

    import Checkbox from "#view/snippets/Checkbox.svelte";
    import FieldWrapper from "#view/snippets/FieldWrapper.svelte";
    import Section from "#view/snippets/Section.svelte";
    import RadioGroup from "#view/snippets/RadioGroup.svelte";

    let item: any = getContext("item");
    let itemStore = $derived(item.reactive.system);
    const { A5E } = CONFIG;
    const isGM = game.user?.isGM;

    let editMode = $state(false);
    let hideBrokenAndDamaged = game.settings.get("a5e", "hideBrokenAndDamaged");
    let showVRCTechLevel = game.settings.get("a5e", "showVRCTechLevel");
    let showVRCImplants = game.settings.get("a5e", "showVRCImplants");
</script>

<Section
    heading="A5E.TabObjectProperties"
    headerButtons={[
        {
            classes: `icon fa-solid ${editMode ? "fa-chevron-up" : "fa-edit"}`,
            handler: () => (editMode = !editMode),
        },
    ]}
    --a5e-section-body-gap="0.75rem"
    --a5e-section-heading-gap="0.5rem"
    --a5e-section-heading-template-columns="max-content max-content"
>
    {#if editMode}
        <RadioGroup
            heading="A5E.ObjectTypePrompt"
            options={Object.entries(A5E.objectTypes)}
            selected={itemStore.objectType}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(item, "system.objectType", value)}
        />

        <RadioGroup
            heading="A5E.ItemRarity"
            options={Object.entries(A5E.itemRarity)}
            selected={itemStore.rarity}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(item, "system.rarity", value)}
        />

        {#if showVRCTechLevel}
            <RadioGroup
                heading="A5E.ItemTechnologyLevel"
                options={Object.entries(A5E.itemTechLevels)}
                selected={itemStore.techLevel}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(
                        item,
                        "system.techLevel",
                        value,
                    )}
            />
        {/if}

        <Section
            --a5e-section-body-direction="row"
            --a5e-section-body-gap="0.75rem"
        >
            <Checkbox
                label="A5E.AttunementRequiredPrompt"
                checked={itemStore.requiresAttunement}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(
                        item,
                        "system.requiresAttunement",
                        value,
                    )}
            />

            {#if item.actor && itemStore.requiresAttunement}
                <Checkbox
                    label="A5E.AttunementPrompt"
                    checked={itemStore.attuned}
                    onUpdateSelection={(value) =>
                        updateDocumentDataFromField(
                            item,
                            "system.attuned",
                            value,
                        )}
                />
            {/if}

            {#if isGM}
                <Checkbox
                    label="A5E.PlotItem"
                    checked={itemStore.plotItem}
                    onUpdateSelection={(value) =>
                        updateDocumentDataFromField(
                            item,
                            "system.plotItem",
                            value,
                        )}
                />

                <Checkbox
                    label="A5E.ItemUnidentified"
                    checked={itemStore.unidentified}
                    onUpdateSelection={(value) =>
                        updateDocumentDataFromField(
                            item,
                            "system.unidentified",
                            value,
                        )}
                />
            {/if}

            {#if itemStore.objectType == "consumable"}
                <Checkbox
                    label="A5E.Supply"
                    checked={itemStore.supply}
                    onUpdateSelection={(value) =>
                        updateDocumentDataFromField(
                            item,
                            "system.supply",
                            value,
                        )}
                />
            {/if}

            {#if showVRCImplants}
                <Checkbox
                    label="A5E.Implant"
                    checked={itemStore.implant}
                    onUpdateSelection={(value) =>
                        updateDocumentDataFromField(
                            item,
                            "system.implant",
                            value,
                        )}
                />
            {/if}
        </Section>

        {#if itemStore.requiresAttunement}
            <FieldWrapper heading="A5E.AttunementHint">
                <input
                    class="a5e-input a5e-input--slim"
                    type="text"
                    value={itemStore.attunementHint}
                    id="{item.uuid}-attunementHint"
                    onchange={({ currentTarget }) =>
                        updateDocumentDataFromField(
                            item,
                            "system.attunementHint",
                            currentTarget.value,
                        )}
                />
            </FieldWrapper>
        {/if}

        <FieldWrapper
            heading="A5E.ItemWeight"
            --a5e-field-wrapper-gap="0.375rem 1rem"
            --a5e-field-wrapper-direction="row"
            --a5e-field-wrapper-header-width="100%"
        >
            <input
                class="a5e-input a5e-input--slim a5e-input--small"
                type="number"
                id="{item.uuid}-weight"
                value={itemStore.weight}
                onchange={({ currentTarget }) =>
                    updateDocumentDataFromField(
                        item,
                        "system.weight",
                        Number(currentTarget.value),
                    )}
            />

            <span>{localize("A5E.DetailsWeightLbs")}</span>

            <Checkbox
                label="A5E.ItemBulky"
                checked={itemStore.bulky}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(item, "system.bulky", value)}
            />
        </FieldWrapper>

        <RadioGroup
            heading="A5E.ItemEquippedState"
            options={Object.entries(A5E.equippedStates)}
            selected={itemStore.equippedState}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(
                    item,
                    "system.equippedState",
                    parseInt(value, 10),
                )}
        />

        <FieldWrapper heading="A5E.ItemQuantity">
            <input
                class="a5e-input a5e-input--slim a5e-input--small"
                type="number"
                min="0"
                max="9999"
                id="{item.uuid}-quantity"
                value={itemStore.quantity}
                onchange={({ currentTarget }) =>
                    updateDocumentDataFromField(
                        item,
                        "system.quantity",
                        Number(currentTarget.value),
                    )}
            />
        </FieldWrapper>

        <FieldWrapper heading="A5E.ItemPrice">
            <input
                class="a5e-input a5e-input--slim a5e-input--small"
                type="text"
                id="{item.uuid}-price"
                value={itemStore.price}
                onchange={({ currentTarget }) =>
                    updateDocumentDataFromField(
                        item,
                        "system.price",
                        currentTarget.value,
                    )}
            />
        </FieldWrapper>

        <FieldWrapper heading="A5E.CraftingComponents">
            <input
                class="a5e-input a5e-input--slim"
                type="text"
                value={itemStore.craftingComponents}
                id="{item.uuid}-craftingComponents"
                onchange={({ currentTarget }) =>
                    updateDocumentDataFromField(
                        item,
                        "system.craftingComponents",
                        currentTarget.value,
                    )}
            />
        </FieldWrapper>

        {#if !hideBrokenAndDamaged}
            <RadioGroup
                heading="A5E.ItemCondition"
                options={Object.entries(A5E.damagedStates)}
                selected={itemStore.damagedState}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(
                        item,
                        "system.damagedState",
                        parseInt(value, 10),
                    )}
            />
        {/if}
    {:else}
        <dl class="a5e-dl-box">
            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ObjectTypePrompt")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {A5E.objectTypes[itemStore.objectType] ??
                        localize("A5E.None")}
                </dd>
            </div>

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ItemRarity")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {A5E.itemRarity[itemStore.rarity] ?? itemStore.rarity}
                </dd>
            </div>

            {#if showVRCTechLevel}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.ItemTechnologyLevel")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {A5E.itemTechLevels[itemStore.techLevel] ??
                            itemStore.techLevel}
                    </dd>
                </div>
            {/if}

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.Attunement")}
                </dt>

                <dd class="a5e-dl-box__content">
                    {#if itemStore.requiresAttunement}
                        {localize("A5E.AttunementRequired")}: ({localize(
                            itemStore.attuned
                                ? "A5E.Attuned"
                                : "A5E.AttunedNot",
                        )})
                    {:else}
                        {localize("A5E.AttunementNotRequired")}
                    {/if}
                </dd>
            </div>

            {#if itemStore.attunementHint !== ""}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.AttunementHint")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {itemStore.attunementHint}
                    </dd>
                </div>
            {/if}

            <hr class="a5e-rule" />

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ItemWeight")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {itemStore.weight}
                    {localize("A5E.DetailsWeightLbs")}

                    {#if itemStore.bulky}
                        <span class="a5e-dl-box__content--bulky">
                            {localize("A5E.ItemBulky")}
                        </span>
                    {/if}
                </dd>
            </div>

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ItemQuantity")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {itemStore.quantity || 0}
                </dd>
            </div>

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.ItemPrice")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {itemStore.price || localize("A5E.None")}
                </dd>
            </div>

            {#if itemStore.craftingComponents !== ""}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.CraftingComponents")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {itemStore.craftingComponents ?? localize("A5E.None")}
                    </dd>
                </div>
            {/if}
        </dl>
    {/if}
</Section>

// src/vue/sheets/pages/partials/config/ObjectConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Object Properties</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.ObjectTypePrompt">
        <update-wrapper
          :document="item"
          updatePath="data.objectType"
          v-slot="slotProps"
        >
          <radio-group
            :options="Object.entries(config.objectTypes)"
            :selected="data.data.objectType"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section heading="A5E.ItemRarity">
        <update-wrapper
          :document="item"
          updatePath="data.rarity"
          v-slot="slotProps"
        >
          <radio-group
            :options="Object.entries(config.itemRarity)"
            :selected="data.data.rarity"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section>
        <div class="u-flex u-gap-xxxl u-text-sm u-w-full">
          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.requiresAttunement"
              :id="`${appId}-attunement-required`"
              :checked="data.data.requiresAttunement"
            />

            <label class="u-pointer" :for="`${appId}-attunement-required`">
              {{ localize("A5E.AttunementRequiredPrompt") }}
            </label>
          </div>

          <div
            v-if="data.data.requiresAttunement"
            class="u-align-center u-flex u-gap-md"
          >
            <input
              class="u-pointer"
              type="checkbox"
              name="data.attuned"
              :id="`${appId}-attuned`"
              :checked="data.data.attuned"
            />

            <label class="u-pointer" :for="`${appId}-attuned`">
              {{ localize("A5E.AttunementPrompt") }}
            </label>
          </div>

          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.plotItem"
              :id="`${appId}-plot-item`"
              :checked="data.data.plotItem"
            />

            <label class="u-pointer" :for="`${appId}-plot-item`">
              {{ localize("A5E.PlotItem") }}
            </label>
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemWeight">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="align-center u-flex u-gap-xxl">
            <div class="u-w-30">
              <input
                type="text"
                name="data.weight"
                :id="`${appId}-weight`"
                :value="data.data.weight"
              />
            </div>

            <div class="u-align-center u-flex u-gap-md">
              <input
                class="u-pointer"
                type="checkbox"
                name="data.bulky"
                :id="`${appId}-bulky`"
                :checked="data.data.bulky"
              />

              <label class="u-pointer" :for="`${appId}-bulky`">
                {{ localize("A5E.ItemBulky") }}
              </label>
            </div>

            <div class="u-align-center u-flex u-gap-md">
              <input
                class="u-pointer"
                type="checkbox"
                name="data.equipped"
                :id="`${appId}-equipped`"
                :checked="data.data.equipped"
              />

              <label class="u-pointer" :for="`${appId}-equipped`">
                {{ localize("A5E.ItemEquipped") }}
              </label>
            </div>
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemQuantity">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-w-20">
            <input
              type="number"
              data-dtype="Number"
              min="0"
              name="data.quantity"
              :id="`${appId}-quantity`"
              :value="data.data.quantity"
            />
          </div>
        </div>
      </form-section>

      <form-section heading="A5E.ItemPrice">
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-w-30">
            <input
              class="u-pl-lg"
              type="text"
              data-dtype="String"
              name="data.price"
              :id="`${appId}-price`"
              :value="data.data.price"
            />
          </div>
        </div>
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ObjectTypePrompt") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{
            localize(
              config.objectTypes[data.data.objectType] ?? data.data.objectType
            )
          }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemRarity") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{
            localize(config.itemRarity[data.data.rarity] ?? data.data.rarity)
          }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.Attunement") }}:</dt>
        <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
          <template v-if="data.data.requiresAttunement">
            {{ localize("A5E.AttunementRequired") }}

            ({{
              localize(data.data.attuned ? "A5E.Attuned" : "A5E.AttunedNot")
            }})
          </template>

          <template v-else>
            {{ localize("A5E.AttunementNotRequired") }}
          </template>
        </dd>
      </div>

      <hr class="a5e-rule u-my-sm" />

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemWeight") }}:</dt>
        <dd class="align-center u-flex u-gap-sm u-m-0 u-p-0">
          {{ data.data.weight }}

          <template v-if="data.data.bulky">
            ({{ localize("A5E.ItemBulky") }})
          </template>
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemQuantity") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ data.data.quantity || 0 }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.ItemPrice") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ data.data.price || 0 }}
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { inject, ref } from "vue";

import FormSection from "../../../../forms/FormSection.vue";
import RadioGroup from "../../../../forms/RadioGroup.vue";
import UpdateWrapper from "../../../../forms/UpdateWrapper.vue";

export default {
  components: { FormSection, RadioGroup, UpdateWrapper },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
    };
  },
};
</script>
