// src/view/sheets/components/item/SpellConfiguration.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import { localize } from "#utils/localization/localize.ts";

    import { objectEntriesNumberKeyConverter } from "#utils/objectEntriesNumberKeyConverter.ts";
    import updateDocumentDataFromField from "#utils/updateDocumentDataFromField.ts";

    import Checkbox from "#view/snippets/Checkbox.svelte";
    import CheckboxGroup from "#view/snippets/CheckboxGroup.svelte";
    import FieldWrapper from "#view/snippets/FieldWrapper.svelte";
    import RadioGroup from "#view/snippets/RadioGroup.svelte";
    import Section from "#view/snippets/Section.svelte";

    function getRawSpellComponents() {
        return Object.entries(itemStore.components)
            .filter(([, state]) => state)
            .map(([component]) => component);
    }

    function prepareSpellComponents() {
        return Object.entries(itemStore.components)
            .filter(([, state]) => state)
            .map(
                ([component]) =>
                    spellComponentAbbreviations[component] ?? component,
            )
            .join(", ");
    }

    function prepareSecondarySpellSchools() {
        const schools = itemStore.schools.secondary.map(
            (school: string) => spellSchools.secondary[school] ?? school,
        );

        schools.sort((a: string, b: string) => a.localeCompare(b));
        return schools.join(", ");
    }

    let item: any = getContext("item");
    let itemStore = $derived(item.reactive.system);
    const {
        PREPARED_STATES,
        classSpellLists,
        psionicDisciplines,
        spellComponents,
        spellComponentAbbreviations,
        spellLevels,
        spellSchools,
    } = CONFIG.A5E;

    let editMode = $state(false);
    let showVRCPsionicDisciplines = game.settings.get(
        "a5e",
        "showVRCPsionicDisciplines",
    ) as boolean;

    let selectedSpellComponentsList = $derived(getRawSpellComponents());
    let selectedSpellComponents = $derived(prepareSpellComponents());
    let selectedSpellSchools = $derived(prepareSecondarySpellSchools());
</script>

<Section
    heading="A5E.TabSpellConfiguration"
    headerButtons={[
        {
            classes: `icon fa-solid ${editMode ? "fa-chevron-up" : "fa-edit"}`,
            handler: () => (editMode = !editMode),
        },
    ]}
    --a5e-section-body-gap="0.75rem"
    --a5e-section-heading-gap="0.5rem"
    --a5e-section-heading-template-columns="max-content max-content"
>
    {#if editMode}
        <CheckboxGroup
            heading="Classes"
            hint="Select the classes that are eligible to select this spell."
            options={Object.entries(classSpellLists)}
            selected={itemStore.classes}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(item, "system.classes", value)}
        />

        <RadioGroup
            heading="A5E.SpellLevel"
            options={objectEntriesNumberKeyConverter(spellLevels)}
            selected={itemStore.level}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(item, "system.level", value)}
        />

        <RadioGroup
            heading="A5E.SpellSchoolPrimary"
            options={Object.entries(spellSchools.primary)}
            selected={itemStore.schools.primary}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(
                    item,
                    "system.schools.primary",
                    value,
                )}
        />

        {#if showVRCPsionicDisciplines}
            <RadioGroup
                heading="A5E.PsionicDiscipline"
                options={Object.entries(psionicDisciplines)}
                selected={itemStore.discipline}
                onUpdateSelection={(value) =>
                    updateDocumentDataFromField(
                        item,
                        "system.discipline",
                        value,
                    )}
            />
        {/if}

        <CheckboxGroup
            heading="A5E.SpellSchoolSecondaryPlural"
            options={Object.entries(spellSchools.secondary)}
            selected={itemStore.schools.secondary}
            onUpdateSelection={(value) =>
                updateDocumentDataFromField(
                    item,
                    "system.schools.secondary",
                    value,
                )}
        />

        <CheckboxGroup
            heading="A5E.SpellComponents"
            options={Object.entries(spellComponents)}
            selected={selectedSpellComponentsList}
            onUpdateSelection={(value) => {
                const updates = {};
                Object.entries(itemStore.components ?? {}).forEach(([key]) => {
                    if (value.includes(key)) updates[key] = true;
                    else updates[key] = false;
                });

                updateDocumentDataFromField(item, "system.components", updates);
            }}
        />

        {#if itemStore.components.material}
            <FieldWrapper heading="A5E.SpellMaterials">
                <input
                    class="a5e-input a5e-input--slim"
                    type="text"
                    value={itemStore.materials}
                    onchange={({ currentTarget }) =>
                        updateDocumentDataFromField(
                            item,
                            "system.materials",
                            currentTarget.value,
                        )}
                />
            </FieldWrapper>
        {/if}

        <Section
            --a5e-section-body-direction="row"
            --a5e-section-body-gap="0.75rem"
        >
            <Checkbox
                label="A5E.SpellConcentration"
                checked={itemStore.concentration}
                onUpdateSelection={(value) => {
                    updateDocumentDataFromField(
                        item,
                        "system.concentration",
                        value,
                    );
                }}
            />

            <Checkbox
                label="A5E.ItemPrepared"
                checked={itemStore.prepared}
                onUpdateSelection={(value) => {
                    updateDocumentDataFromField(item, "system.prepared", value);
                }}
            />

            {#if itemStore.prepared}
                <Checkbox
                    label="Always Prepared"
                    checked={Number(itemStore.prepared ?? 0) ===
                        PREPARED_STATES.ALWAYS_PREPARED}
                    onUpdateSelection={(checked) => {
                        updateDocumentDataFromField(
                            item,
                            "system.prepared",
                            checked ? 2 : 1,
                        );
                    }}
                />
            {/if}

            {#if itemStore.level > 0}
                <Checkbox
                    label="A5E.SpellRitual"
                    checked={itemStore.ritual}
                    onUpdateSelection={(value) => {
                        updateDocumentDataFromField(
                            item,
                            "system.ritual",
                            value,
                        );
                    }}
                />
            {/if}

            <Checkbox
                label="A5E.SpellRare"
                checked={itemStore.rare}
                onUpdateSelection={(value) => {
                    updateDocumentDataFromField(item, "system.rare", value);
                }}
            />
        </Section>

        <Section
            --a5e-section-body-direction="row"
            --a5e-section-body-gap="0.75rem"
        >
            <FieldWrapper>
                <Checkbox
                    label="A5E.RequiresBloodied"
                    checked={itemStore.requiresBloodied}
                    onUpdateSelection={(value) => {
                        updateDocumentDataFromField(
                            item,
                            "system.requiresBloodied",
                            value,
                        );
                    }}
                />
            </FieldWrapper>
        </Section>
    {:else}
        <dl class="a5e-dl-box">
            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.SpellLevel")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {spellLevels[itemStore.level] ?? itemStore.level}
                </dd>
            </div>

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.SpellSchoolPrimary")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {spellSchools.primary[itemStore.schools.primary] ||
                        localize("A5E.None")}
                </dd>
            </div>

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.SpellSchoolSecondaryPlural")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {selectedSpellSchools || localize("A5E.None")}
                </dd>
            </div>

            {#if showVRCPsionicDisciplines}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.PsionicDiscipline")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {localize(psionicDisciplines[itemStore.diiscipline]) ||
                            localize("A5E.None")}
                    </dd>
                </div>
            {/if}

            <hr class="a5e-rule" />

            <div class="a5e-dl-box__section">
                <dt class="a5e-dl-box__header">
                    {localize("A5E.SpellComponents")}:
                </dt>

                <dd class="a5e-dl-box__content">
                    {selectedSpellComponents || localize("A5E.None")}
                </dd>
            </div>

            {#if itemStore.components.material && itemStore.materials}
                <div class="a5e-dl-box__section">
                    <dt class="a5e-dl-box__header">
                        {localize("A5E.SpellMaterials")}:
                    </dt>

                    <dd class="a5e-dl-box__content">
                        {itemStore.materials}
                    </dd>
                </div>
            {/if}
        </dl>
    {/if}
</Section>

// src/vue/sheets/pages/partials/config/SpellConfiguration.vue
<template>
  <section>
    <header
      class="
        u-align-center
        u-flex
        u-font-serif
        u-gap-md
        u-mb-lg
        u-ml-xs
        u-pointer
        u-text-lg
        u-w-fit
      "
      @click="editModeActive = !editModeActive"
    >
      <h3>Spell Properties</h3>
      <i
        class="u-text-sm fas"
        :class="editModeActive ? 'fa-chevron-up' : 'fa-edit'"
      ></i>
    </header>

    <div v-if="editModeActive" class="u-flex u-flex-col u-gap-md">
      <form-section heading="A5E.SpellLevel">
        <update-wrapper
          :document="item"
          updatePath="data.level"
          v-slot="slotProps"
        >
          <radio-group
            :options="Object.entries(config.spellLevels)"
            :selected="data.data.level"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section heading="A5E.SpellSchoolPrimary">
        <update-wrapper
          :document="item"
          updatePath="data.schools.primary"
          v-slot="slotProps"
        >
          <radio-group
            :options="Object.entries(config.spellSchools.primary)"
            :selected="data.data.schools.primary"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section heading="A5E.SpellSchoolSecondaryPlural">
        <update-wrapper
          :document="item"
          updatePath="data.schools.secondary"
          v-slot="slotProps"
        >
          <checkbox-group
            :options="Object.entries(config.spellSchools.secondary)"
            :selected="data.data.schools.secondary"
            :selectionHandler="slotProps.selectionHandler"
          />
        </update-wrapper>
      </form-section>

      <form-section heading="A5E.SpellComponents">
        <ul
          class="
            u-flex
            u-flex-wrap
            u-gap-sm
            u-list-style-none
            u-m-0
            u-p-0
            u-text-xs
            u-w-full
          "
        >
          <option-tag
            v-for="[value, label] in Object.entries(config.spellComponents)"
            :key="value"
            v-bind="{ label, value }"
            :selected="data.data.components[value]"
            @option-selected="onUpdateSpellComponentSelection"
          />
        </ul>
      </form-section>

      <form-section
        v-if="data.data.components.material"
        heading="A5E.SpellMaterials"
      >
        <div class="u-w-full">
          <input
            class="a5e-input"
            name="data.materials"
            type="text"
            :value="data.data.materials"
          />
        </div>
      </form-section>

      <form-section>
        <div
          class="u-align-center u-flex u-flex-wrap u-gap-md u-text-sm u-w-full"
        >
          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.concentration"
              :id="`${appId}-concentration`"
              :checked="data.data.concentration"
            />

            <label class="u-pointer" :for="`${appId}-concentration`">
              {{ localize("A5E.SpellConcentration") }}
            </label>
          </div>

          <div class="u-align-center u-flex u-gap-md">
            <input
              class="u-pointer"
              type="checkbox"
              name="data.prepared"
              :id="`${appId}-prepared`"
              :checked="data.data.prepared"
            />

            <label class="u-pointer" :for="`${appId}-prepared`">
              {{ localize("A5E.ItemPrepared") }}
            </label>
          </div>

          <div
            v-if="data.data.level > 0"
            class="u-align-center u-flex u-gap-md"
          >
            <input
              class="u-pointer"
              type="checkbox"
              name="data.ritual"
              :id="`${appId}-ritual`"
              :checked="data.data.ritual"
            />

            <label class="u-pointer" :for="`${appId}-ritual`">
              {{ localize("A5E.SpellRitual") }}
            </label>
          </div>
        </div>
      </form-section>
    </div>

    <dl
      v-else
      class="a5e-box u-flex u-flex-col u-gap-sm u-m-0 u-p-md u-text-sm"
    >
      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellLevel") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ localize(config.spellLevels[data.data.level]) }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellSchoolPrimary") }}:</dt>
        <dd class="u-m-0 u-p-0">
          {{ localize(config.spellSchools.primary[data.data.schools.primary]) }}
        </dd>
      </div>

      <div class="u-flex u-gap-md">
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.SpellSchoolSecondaryPlural") }}:
        </dt>

        <dd class="u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-wrap
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
            "
            v-if="data.data.schools.secondary.length"
          >
            <li
              v-for="school in data.data.schools.secondary.sort((a, b) =>
                a.toLowerCase().localeCompare(b.toLowerCase())
              )"
              :key="school"
            >
              {{ localize(config.spellSchools.secondary[school] ?? school) }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>

      <hr class="a5e-rule u-my-sm" />

      <div class="u-flex u-gap-md">
        <dt class="u-text-bold">{{ localize("A5E.SpellComponents") }}:</dt>
        <dd class="u-flex u-gap-ch u-m-0 u-p-0">
          <ul
            class="
              u-comma-list
              u-flex
              u-flex-shrink-0
              u-gap-ch
              u-list-style-none
              u-m-0
              u-p-0
              u-w-fit
            "
            v-if="Object.values(data.data.components).some(Boolean)"
          >
            <li
              v-for="[component] in Object.entries(data.data.components).filter(
                ([_, state]) => state
              )"
              :key="component"
            >
              {{
                localize(
                  `${config.spellComponents[component]}Abbr` ?? component
                )
              }}
            </li>
          </ul>

          <template v-else>
            {{ localize("A5E.None") }}
          </template>
        </dd>
      </div>

      <div
        v-if="data.data.components.material && data.data.materials"
        class="u-flex u-gap-md"
      >
        <dt class="u-flex-shrink-0 u-text-bold">
          {{ localize("A5E.SpellMaterials") }}:
        </dt>

        <dd class="u-m-0 u-p-0">
          {{ data.data.materials }}
        </dd>
      </div>
    </dl>
  </section>
</template>

<script>
import { inject, ref, watch } from "vue";

import CheckboxGroup from "../../../../forms/CheckboxGroup.vue";
import FormSection from "../../../../forms/FormSection.vue";
import OptionTag from "../../../../forms/OptionTag.vue";
import RadioGroup from "../../../../forms/RadioGroup.vue";
import UpdateWrapper from "../../../../forms/UpdateWrapper.vue";

export default {
  components: {
    CheckboxGroup,
    FormSection,
    OptionTag,
    RadioGroup,
    UpdateWrapper,
  },
  setup() {
    const appId = inject("appId");
    const data = inject("data");
    const item = inject("item");

    const editModeActive = ref(false);

    watch(
      () => data.value.data.level,
      (level) => {
        if (parseInt(level, 10) === 0) {
          item.update({ "data.ritual": false });
        }
      }
    );

    function onUpdateSpellComponentSelection(key) {
      item.update({
        [`data.components.${key}`]: !data.value.data.components[key],
      });
    }

    return {
      appId,
      config: CONFIG.A5E,
      data,
      editModeActive,
      item,
      localize: (key) => game.i18n.localize(key),
      onUpdateSpellComponentSelection,
    };
  },
};
</script>
