// src/apps/components/actorSidebar/Initiative.svelte
<script>
    import { getContext } from "svelte";

    import pressedKeysStore from "../../../stores/pressedKeysStore";
    import getKeyPressAsOptions from "../../handlers/getKeyPressAsOptions";

    const actor = getContext("actor");

    $: sheetIsLocked = $actor.flags?.a5e?.sheetIsLocked ?? true;
</script>

<li>
    <h4 class="initiative-label">Initiative</h4>

    {#if sheetIsLocked}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <i
            class="initiative-roll-button fas fa-dice-d20"
            class:initiative-roll-button--shift={$pressedKeysStore.ShiftLeft}
            class:initiative-roll-button--ctrl={$pressedKeysStore.ControlLeft}
            data-tooltip="A5E.RollInitiative"
            data-tooltip-direction="DOWN"
            on:click={() =>
                $actor.rollInitiative({
                    createCombatants: true,
                    initiativeOptions: {
                        rollOptions: getKeyPressAsOptions($pressedKeysStore, {
                            reverseAlt: game.settings.get(
                                "a5e",
                                "reverseInitiativeAltBehavior"
                            ),
                        }),
                    },
                })}
        />
    {:else}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <i
            class="initiative-roll-button fas fa-cog"
            data-tooltip="A5E.InitiativeConfigurationTitle"
            data-tooltip-direction="DOWN"
            on:click={() => $actor.configureInitiative()}
        />
    {/if}
</li>

<style lang="scss">
    .initiative-roll-button {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-grow: 1;
        color: #7e7960;
        font-size: 1.44rem;
        width: 2.5rem;
        height: 2.5rem;
        margin: auto;
        cursor: pointer;

        transition: all 0.15s ease-in-out;

        &:hover {
            transform: scale(1.2);
            color: #555;
        }

        &--ctrl:hover {
            color: #ffb63b;
        }

        &--shift:hover {
            color: #488f9a;
        }
    }

    .initiative-label {
        font-size: 1rem;
        text-align: center;
        padding-bottom: 0.125rem;
    }
</style>

// src/vue/sheets/header/partials/Initiative.vue
<template>
  <li
    class="
      u-align-center
      u-bg-gray
      u-flex
      u-flex-col
      u-justify-space-between
      u-py-xs
      u-rounded
      u-w-full
    "
  >
    <h4 class="u-text-lg">{{ localize("A5E.Initiative") }}</h4>

    <i
      class="
        u-hover-scale-120
        u-hover-text-inherit
        u-text-medium
        u-pointer
        u-text-lg
        u-transition-transform
        fas
        fa-dice-d20
      "
      :class="{ 'u-mb-xl u-text-xl': sheetIsLocked }"
      @click="onRollInitiative"
    ></i>

    <div
      v-if="!sheetIsLocked"
      class="a5e-ability-score__buttons u-justify-center"
    >
      <i
        class="a5e-config-button fas fa-cog"
        title="Configure Initiative Bonuses"
        @click="onClickConfigButton"
      ></i>
    </div>
  </li>
</template>

<script>
import { inject } from "vue";

export default {
  props: { sheetIsLocked: Boolean },
  setup() {
    const actor = inject("actor");

    function onClickConfigButton() {
      actor.configureInitiative();
    }

    function onRollInitiative() {
      actor.rollInitiative({ createCombatants: true });
    }

    return {
      localize: (key) => game.i18n.localize(key),
      onClickConfigButton,
      onRollInitiative,
    };
  },
};
</script>
